// Code completely AI generated by OpenCode with Big Pickle
// Will be used if there are problems with real hardware, for now no need to use it
use std::fs::OpenOptions;
use std::io::{Read, Seek, SeekFrom, Write};
use std::path::Path;

fn crc32(data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFFFFFF;
    for &byte in data {
        crc ^= byte as u32;
        for _ in 0..8 {
            if crc & 1 != 0 { crc = (crc >> 1) ^ 0xEDB88320; } else { crc >>= 1; }
        }
    }
    crc ^ 0xFFFFFFFF
}

pub fn apply_el_torito_patch(iso_path: &Path) -> std::io::Result<()> {
    let mut file = OpenOptions::new()
        .read(true)
        .write(true)
        .open(iso_path)?;

    let iso_size = file.metadata()?.len();
    let n512 = (iso_size / 512) as u64;

    // ── 1. Find BRVD and catalog LBA ──
    let mut brvd_sector = None;
    for sector in 16..32 {
        let offset = sector * 2048;
        file.seek(SeekFrom::Start(offset))?;
        let mut buf = [0u8; 6];
        file.read_exact(&mut buf)?;
        if buf[0] == 0 && &buf[1..6] == b"CD001" {
            brvd_sector = Some(sector);
            break;
        }
    }
    let brvd_sector = brvd_sector.ok_or_else(|| {
        std::io::Error::new(std::io::ErrorKind::NotFound,
            "Could not locate El Torito BRVD")
    })?;

    file.seek(SeekFrom::Start((brvd_sector * 2048) + 71))?;
    let mut lba_bytes = [0u8; 4];
    file.read_exact(&mut lba_bytes)?;
    let catalog_lba = u32::from_le_bytes(lba_bytes);
    let catalog_offset = (catalog_lba as u64) * 2048;
    println!("-> [Patch] Boot Catalog at LBA: {}", catalog_lba);

    // ── 2. Read catalog and find UEFI image LBA ──
    let mut catalog = [0u8; 2048];
    file.seek(SeekFrom::Start(catalog_offset))?;
    file.read_exact(&mut catalog)?;

    let image_lba = u32::from_le_bytes([catalog[104], catalog[105], catalog[106], catalog[107]]);

    // ── 3. Read FAT BPB at image LBA ──
    let image_offset = (image_lba as u64) * 2048;
    let mut bpb = [0u8; 512];
    file.seek(SeekFrom::Start(image_offset))?;
    file.read_exact(&mut bpb)?;

    // Zero hidden sectors
    let hidden = u32::from_le_bytes([bpb[28], bpb[29], bpb[30], bpb[31]]);
    if hidden != 0 {
        file.seek(SeekFrom::Start(image_offset + 28))?;
        file.write_all(&[0x00; 4])?;
        println!("-> [Patch] Zeroed hidden sectors (was 0x{:X})", hidden);
    }

    // Compute sector count
    let tot32 = u32::from_le_bytes([bpb[32], bpb[33], bpb[34], bpb[35]]);
    let tot16 = u16::from_le_bytes([bpb[19], bpb[20]]);
    let fat_total = if tot32 > 0 { tot32 } else { tot16 as u32 };
    let bytes_per_sec = u16::from_le_bytes([bpb[11], bpb[12]]);
    let correct_sectors = if fat_total > 0 {
        (fat_total * bytes_per_sec as u32 / 512) as u16
    } else { 0 };
    println!("-> [Patch] FAT image: LBA={}, sectors={}", image_lba, correct_sectors);

    // ── 4. Fix El Torito catalog ──
    //    Make Default Entry non-bootable, fix UEFI entry sector count.
    let mut changes = 0;
    if catalog[32] != 0x00 { catalog[32] = 0x00; changes += 1; }
    let uefi_sectors = u16::from_le_bytes([catalog[102], catalog[103]]);
    if uefi_sectors != correct_sectors {
        catalog[102] = (correct_sectors & 0xFF) as u8;
        catalog[103] = (correct_sectors >> 8) as u8;
        changes += 1;
    }
    if changes > 0 {
        file.seek(SeekFrom::Start(catalog_offset))?;
        file.write_all(&catalog)?;
        println!("-> [Patch] Fixed catalog: {} byte(s)", changes);
    }

    // ── 5. Fix GPT: write valid ESP partition ──
    //    The GPT header at LBA 1 points partition entries to LBA 34, but the
    //    actual partition entry data sits at LBA 2 (standard location).  Fix
    //    the header to point to LBA 2 and write a proper ESP partition entry.
    //    Also update the backup header at the last LBA.

    let esp_start_512 = (image_lba as u64) * 2048 / 512; // 208
    let esp_size_512 = correct_sectors as u64; // 3163
    let esp_end_512 = esp_start_512 + esp_size_512 - 1; // 3370

    // Build ESP partition entry (128 bytes)
    let esp_guid: [u8; 16] = [
        0x28, 0x73, 0x2A, 0xC1, 0x1F, 0xF8, 0xD2, 0x11,
        0xBA, 0x4B, 0x00, 0xA0, 0xC9, 0x3E, 0xC9, 0x3B,
    ];
    let part_guid: [u8; 16] = [
        0xFF, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0x11, 0x22,
        0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xAA,
    ];
    let mut entry = [0u8; 128];
    entry[0..16].copy_from_slice(&esp_guid);
    entry[16..32].copy_from_slice(&part_guid);
    entry[32..40].copy_from_slice(&esp_start_512.to_le_bytes());
    entry[40..48].copy_from_slice(&esp_end_512.to_le_bytes());
    entry[48..56].copy_from_slice(&[0u8; 8]); // attributes
    let name_utf16: &[u16] = &[
        'E' as u16, 'F' as u16, 'I' as u16, ' ' as u16,
        'S' as u16, 'y' as u16, 's' as u16, 't' as u16,
        'e' as u16, 'm' as u16, ' ' as u16, 'P' as u16,
        'a' as u16, 'r' as u16, 't' as u16,
    ];
    for (i, &ch) in name_utf16.iter().enumerate() {
        let b = ch.to_le_bytes();
        entry[56 + i*2] = b[0];
        entry[56 + i*2 + 1] = b[1];
    }

    // Primary partition table at LBA 2 (standard location)
    let pt_primary_lba = 2u64;
    let pt_backup_lba = n512 - 1 - 32; // 3375

    file.seek(SeekFrom::Start(pt_primary_lba * 512))?;
    file.write_all(&entry)?;
    file.seek(SeekFrom::Start(pt_backup_lba * 512))?;
    file.write_all(&entry)?;

    // ── 6. Update primary GPT header at LBA 1 ──
    //     Fix partition entry LBA (offset 72) from 34 to 2.
    //     Recalculate partition entries CRC and header CRC.
    let pt_size: u64 = 128 * 128; // 128 entries × 128 bytes = 16384
    let mut pt_data = vec![0u8; pt_size as usize];
    file.seek(SeekFrom::Start(pt_primary_lba * 512))?;
    file.read_exact(&mut pt_data)?;
    let pt_crc_primary = crc32(&pt_data);

    file.seek(SeekFrom::Start(pt_backup_lba * 512))?;
    file.read_exact(&mut pt_data)?;
    let pt_crc_backup = crc32(&pt_data);

    for &(hdr_lba, pt_lba, pt_crc) in &[
        (1u64, pt_primary_lba, pt_crc_primary),
        (n512 - 1, pt_backup_lba, pt_crc_backup),
    ] {
        let hdr_off = hdr_lba * 512;
        let mut hdr = [0u8; 92];
        file.seek(SeekFrom::Start(hdr_off))?;
        file.read_exact(&mut hdr)?;

        // Fix partition entry LBA in header
        hdr[72..80].copy_from_slice(&pt_lba.to_le_bytes());
        // Set partition entries CRC
        hdr[88..92].copy_from_slice(&pt_crc.to_le_bytes());

        // Recalculate header CRC (zero the CRC field first)
        hdr[16..20].copy_from_slice(&[0u8; 4]);
        let hdr_crc = crc32(&hdr);
        hdr[16..20].copy_from_slice(&hdr_crc.to_le_bytes());

        file.seek(SeekFrom::Start(hdr_off))?;
        file.write_all(&hdr)?;
        println!("-> [Patch] GPT hdr LBA={}: pt_lba={}, hdr_crc=0x{:08X}, pt_crc=0x{:08X}",
            hdr_lba, pt_lba, hdr_crc, pt_crc);
    }

    println!("-> [Patch] Done.");
    Ok(())
}
